apiVersion: v1
kind: PersistentVolume
metadata:
  name: "codescene-data"
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: YOUR-EBS-VOLUME-ID
    fsType: ext4
