apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: codescene-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - hosts:
    - "*"
    port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: false # sends 301 redirect for http requests
  - hosts:
    - "*"
    port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: codescene
spec:
  hosts:
  - "codescene.k8s-pcconsultants.de"
  gateways:
  - codescene-gateway
  http:
  - match:
    - uri:
        prefix: /login
    - uri:
        prefix: /
    route:
    - destination:
        host: codescene.codescene.svc.cluster.local
        port:
          number: 3003
